"""empty message

Revision ID: 33eb41bb67fc
Revises: c5c559958c84
Create Date: 2019-10-17 22:22:45.590211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33eb41bb67fc'
down_revision = 'c5c559958c84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_device_token_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_device_token_key', 'user', ['device_token'])
    # ### end Alembic commands ###
