"""empty message

Revision ID: c5c559958c84
Revises: 57b741529ec9
Create Date: 2019-10-17 22:00:31.760912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c559958c84'
down_revision = '57b741529ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('maktura_plate_number', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'car', ['maktura_plate_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car', type_='unique')
    op.drop_column('car', 'maktura_plate_number')
    # ### end Alembic commands ###
